version: "3"
services:
  small:
    build: .
    image: afrobambacar/small
    container_name: small
    ports:
      - 80:80
    command: bash -c "pm2-docker --public KEYMETRICS_PUBLIC --secret KEYMETRICS_SECRET process.yml"